spring:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/rest

  mail:
    host: smtp.gmail.com
    port: 587
    username:  pomaprokhorovich583@gmail.com
    password: cjmr dgil zdtj afmc
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

mail:
  admin: gzdeww@yandex.ru
  user: potom